apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "papermc.fullname" . }}
  labels:
    {{- include "papermc.labels" . | nindent 4 }}
data:
  {{- range $fileName, $fileContent := .Values.configs }}
  {{- if eq "server.properties" $fileName }}
  {{ $fileName }}: |-
    # k8s provisioned file, edit values.yaml to change
    {{- range $k, $v := $fileContent }}
    {{ $k }}={{ $v }}
    {{- end }}
  {{- else if hasSuffix ".yml" $fileName }}
  {{ $fileName }}: |-
    {{- $fileContent | toYaml | nindent 4 }}
  {{- else if hasSuffix ".json" $fileName }}
  {{ $fileName }}: |-
    {{- $fileContent | toJson | nindent 4 }}
  {{- end }}
  {{- end }}