{{- if and .Values.persistence.enabled (not .Values.persistence.existingPVCName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "papermc.fullname" . }}
  labels:
    {{- include "papermc.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}