{{/*
Generate data
*/}}
{{- $authDetails := dict "username" .Values.registryUsername "password" .Values.registryPassword }}
{{- $authDetails := set $authDetails "auth" (printf "%s:%s" .Values.registryUsername .Values.registryPassword | b64enc) }}
{{- if .Values.registryEmail }}
{{- $authDetails := set $authDetails "email" .Values.registryEmail }}
{{- end }}
{{- $registryURL := "" }}
{{- $registryDetails := dict .Values.registryURL $authDetails }}
{{- $dockerConfig := dict "auths" $registryDetails }}

{{/*
Template
*/}}
{{- if .Values.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ $dockerConfig | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}